### Bank

we build a classifier which can determine whether they will leave or
not using Neural networks

### Load tensorflow

In [0]:
import tensorflow as tf
tf.set_random_seed(42)

In [2]:
tf.__version__

'1.13.1'

### Collect Data

In [3]:
import keras

Using TensorFlow backend.


In [4]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
project_path='/content/drive/My Drive/AI_ML/Residency7 lab/Plant_Breed'

In [0]:
import os 
os.chdir(project_path)

In [0]:
from zipfile import ZipFile
with ZipFile('train.zip','r') as f:
  f.extractall()

In [0]:
with ZipFile('test.zip','r') as f:
  f.extractall()

In [0]:
x_test=[]
y_test=[]
os.chdir(project_path+'/test')
import cv2
for i in os.listdir():
    dummy = cv2.imread(i)
    dummy = cv2.resize(dummy,(128,128))
    x_test.append(dummy)
    y_test.append(i)

In [0]:
x_train = []
y_train = []

In [0]:
os.chdir(project_path+'/train')

In [24]:
x_train = []
y_train = []
import cv2
for i in os.listdir():
    print("dir",i)
    if (os.path.isdir(i)):
            for j in os.listdir(i):
                try:
                    dummy = cv2.imread(project_path+'/train/' + i + "/" + j)
                    dummy = cv2.resize(dummy,(128,128))
                    x_train.append(dummy)
                    y_train.append(i)
                except Exception as e:
                    print(e)


dir Fat Hen
dir Small-flowered Cranesbill
dir Cleavers
dir Black-grass
dir Sugar beet
dir Shepherds Purse
dir Charlock
dir Loose Silky-bent
dir Scentless Mayweed
dir Maize
dir Common Chickweed
dir Common wheat


In [25]:
x_train[0].shape

(128, 128, 3)

In [0]:
y_train_dup=y_train

In [0]:
import pandas as pd
dum = pd.get_dummies(y_train)

In [45]:
dum

Black-grass  Charlock  Cleavers  Common Chickweed  Common wheat  \
0               0         0         0                 0             0   
1               0         0         0                 0             0   
2               0         0         0                 0             0   
3               0         0         0                 0             0   
4               0         0         0                 0             0   
5               0         0         0                 0             0   
6               0         0         0                 0             0   
7               0         0         0                 0             0   
8               0         0         0                 0             0   
9               0         0         0                 0             0   
10              0         0         0                 0             0   
11              0         0         0                 0             0   
12              0         0         0                 0             0   
13              0         0         0                 0             0   
14              0         0         0                 0             0   
15              0         0         0                 0             0   
16              0         0         0                 0             0   
17              0         0         0                 0             0   
18              0         0         0                 0             0   
19              0         0         0                 0             0   
20              0         0         0                 0             0   
21              0         0         0                 0             0   
22              0         0         0                 0             0   
23              0         0         0                 0             0   
24              0         0         0                 0             0   
25              0         0         0                 0             0   
26              0         0         0                 0             0   
27              0         0         0                 0             0   
28              0         0         0                 0             0   
29              0         0         0                 0             0   
...           ...       ...       ...               ...           ...   
4720            0         0         0                 0             1   
4721            0         0         0                 0             1   
4722            0         0         0                 0             1   
4723            0         0         0                 0             1   
4724            0         0         0                 0             1   
4725            0         0         0                 0             1   
4726            0         0         0                 0             1   
4727            0         0         0                 0             1   
4728            0         0         0                 0             1   
4729            0         0         0                 0             1   
4730            0         0         0                 0             1   
4731            0         0         0                 0             1   
4732            0         0         0                 0             1   
4733            0         0         0                 0             1   
4734            0         0         0                 0             1   
4735            0         0         0                 0             1   
4736            0         0         0                 0             1   
4737            0         0         0                 0             1   
4738            0         0         0                 0             1   
4739            0         0         0                 0             1   
4740            0         0         0                 0             1   
4741            0         0         0                 0             1   
4742            0         0         0                 0         

In [0]:
encoded_labels = dum
y_train = dum

In [47]:
import numpy as np
y_train = np.array(y_train)
x_train = np.array(x_train)
x_train[0].shape

(128, 128, 3)

In [48]:
from sklearn.model_selection import train_test_split
x_train2, x_val, y_train2, y_val = train_test_split(x_train, y_train, test_size=0.2, random_state=2)
print (len(x_train2))
print (len(x_val))

3800
950


In [49]:
x_train2[0].shape

(128, 128, 3)

In [0]:
x_train2 = x_train2.reshape(x_train2.shape[0],128,128,3)
x_val = x_val.reshape(x_val.shape[0],128,128,3)

In [51]:
print (x_train2.shape)
print (x_val.shape)

(3800, 128, 128, 3)
(950, 128, 128, 3)


In [52]:
print(y_train2.shape)
print(y_val.shape)

(3800, 12)
(950, 12)


In [0]:
from keras.models import Sequential
from keras.layers import Convolution2D, Dropout, Dense

In [0]:
from keras.layers import BatchNormalization
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.optimizers import adam

In [0]:
model = Sequential()
model.add(BatchNormalization(input_shape = (128,128,3)))
model.add(Convolution2D(32, (3,3), activation ='relu', input_shape = (128, 128, 3))) 
model.add(MaxPooling2D(pool_size=2))
#model.add(Dropout(0.8))

model.add(Convolution2D(filters=64, kernel_size=4, padding='same', activation='relu'))
model.add(MaxPooling2D(pool_size=2))
#model.add(Dropout(0.8))

model.add(Convolution2D(filters=128, kernel_size=3, padding='same', activation='relu'))
model.add(MaxPooling2D(pool_size=2))
#model.add(Dropout(0.8))

model.add(Convolution2D(filters=128, kernel_size=2, padding='same', activation='relu'))
model.add(MaxPooling2D(pool_size=2))
#model.add(Dropout(0.8))

model.add(Flatten()) 

# fully connected layer
model.add(Dense(units=128,activation = 'relu'))
model.add(Dense(units = 64, activation = 'relu'))
#model.add(Dropout(0.3))
model.add(Dense(units = 32, activation = 'relu'))
#model.add(Dropout(0.3))
model.add(Dense(units = 12, activation = 'softmax')) 


In [0]:
optimizer = adam(lr=0.001)
model.compile(optimizer='adam', loss = 'categorical_crossentropy',metrics = ['accuracy'])

In [61]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
batch_normalization_3 (Batch (None, 128, 128, 3)       12        
_________________________________________________________________
conv2d_9 (Conv2D)            (None, 126, 126, 32)      896       
_________________________________________________________________
max_pooling2d_9 (MaxPooling2 (None, 63, 63, 32)        0         
_________________________________________________________________
conv2d_10 (Conv2D)           (None, 63, 63, 64)        32832     
_________________________________________________________________
max_pooling2d_10 (MaxPooling (None, 31, 31, 64)        0         
_________________________________________________________________
conv2d_11 (Conv2D)           (None, 31, 31, 128)       73856     
_________________________________________________________________
max_pooling2d_11 (MaxPooling (None, 15, 15, 128)       0         
__________

In [62]:
batch_size = 64
nb_epochs = 10
history = model.fit(x_train,y_train,
                    epochs=20, 
                    validation_data=(x_val,y_val),
                    verbose = 1,
                    initial_epoch=0)

Instructions for updating:
Use tf.cast instead.
Train on 4750 samples, validate on 950 samples
Epoch 1/20
4750/4750 [==============================] - 14s 3ms/step - loss: 1.6608 - acc: 0.4366 - val_loss: 0.9464 - val_acc: 0.6947
Epoch 2/20
4750/4750 [==============================] - 9s 2ms/step - loss: 0.8869 - acc: 0.7038 - val_loss: 0.7898 - val_acc: 0.7221
Epoch 3/20
4750/4750 [==============================] - 9s 2ms/step - loss: 0.5869 - acc: 0.7979 - val_loss: 0.4231 - val_acc: 0.8537
Epoch 4/20
4750/4750 [==============================] - 9s 2ms/step - loss: 0.4859 - acc: 0.8322 - val_loss: 0.3508 - val_acc: 0.8758
Epoch 5/20
4750/4750 [==============================] - 9s 2ms/step - loss: 0.3416 - acc: 0.8724 - val_loss: 0.2804 - val_acc: 0.9053
Epoch 6/20
4750/4750 [==============================] - 10s 2ms/step - loss: 0.3111 - acc: 0.8840 - val_loss: 0.2731 - val_acc: 0.8863
Epoch 7/20
4750/4750 [==============================] - 9s 2ms/step - loss: 0.2450 - acc: 0.9101 - 

In [0]:
predictions=model.predict(x_val)

In [0]:
y_train_lables=dum.columns

In [0]:
actual_lables=[]
for j in range(len(y_val)):
    actual_value = np.argmax(y_val[j])
    actual_lables.append(y_train_lables[actual_value])

In [89]:
actual_lables[0]

'Common Chickweed'

In [90]:
 np.argmax(y_val[0])

3

In [91]:
y_val[0]

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [69]:
predictions[1]

array([4.3051058e-13, 3.9623842e-12, 1.1856103e-11, 1.0000000e+00,
       2.0962370e-13, 2.5901396e-11, 7.6475971e-11, 9.8025303e-11,
       2.0433392e-13, 2.3456019e-09, 2.7341089e-12, 3.4276520e-13],
      dtype=float32)

In [0]:
import numpy as np
final_predictions=[]
for x in range(len(predictions)):
#Get predicted number with highest probability
  predicted_num = np.argmax(predictions[x])
#Print the number
  final_predictions.append(predicted_num)

In [0]:
final_predicted_labels=[]
for i in final_predictions:
  final_predicted_labels.append(y_train_lables[i])

In [93]:
for j in range(10):
  print("predicted value for",actual_lables[j]," is ",final_predicted_labels[j])

predicted value for Common Chickweed  is  Common Chickweed
predicted value for Common Chickweed  is  Common Chickweed
predicted value for Charlock  is  Charlock
predicted value for Loose Silky-bent  is  Loose Silky-bent
predicted value for Loose Silky-bent  is  Loose Silky-bent
predicted value for Charlock  is  Charlock
predicted value for Scentless Mayweed  is  Scentless Mayweed
predicted value for Fat Hen  is  Fat Hen
predicted value for Fat Hen  is  Fat Hen
predicted value for Common wheat  is  Common wheat


## Review model

In [92]:
from sklearn.metrics import confusion_matrix 
confusion_matrix(actual_lables, final_predicted_labels)

array([[ 46,   0,   0,   0,   1,   0,   5,   0,   0,   0,   0,   0],
       [  0,  70,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,  50,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0, 118,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,  47,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0, 102,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0, 134,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  40,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  90,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  49,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 112,   0],
       [  0,   0,   0,   0,   0,   0,   0,   1,   0,   0,   0,  85]])