# Transfer Learning CIFAR10

* Train a simple convnet on the CIFAR dataset the first 5 output classes [0..4].
* Freeze convolutional layers and fine-tune dense layers for the last 5 ouput classes [5..9].


### 1. Import CIFAR10 data and create 2 datasets with one dataset having classes from 0 to 4 and other having classes from 5 to 9 

In [0]:
import tensorflow as tf
tf.reset_default_graph()
tf.set_random_seed(42)
import numpy as np

In [2]:
from keras.datasets import cifar10

Using TensorFlow backend.


In [3]:
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

170500096/170498071 [==============================] - 15s 0us/step


In [4]:
y_train.shape

(50000, 1)

In [5]:
np.unique(y_train)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [6]:
size1=y_train.shape
size1

(50000, 1)

In [7]:
size2=y_test.shape
size2

(10000, 1)

In [0]:
x_train1=[]
y_train1=[]
x_train2=[]
y_train2=[]

for i in range(size1[0]):
  if(y_train[i]<5):
    x_train1.append(x_train[i])
    y_train1.append(y_train[i])  
  else:
    x_train2.append(x_train[i])
    y_train2.append(y_train[i])


In [0]:
x_test1=[]
y_test1=[]
x_test2=[]
y_test2=[]
for j in range(size2[0]):
  if(y_test[j]<5):
    x_test1.append(x_test[j])
    y_test1.append(y_test[j])
  else:
    x_test2.append(x_test[j])
    y_test2.append(y_test[j])

In [0]:

X_train1=np.asarray(x_train1)
X_train2=np.asarray(x_train2)
Y_train1=np.asarray(y_train1)
Y_train2=np.asarray(y_train2)
X_test1=np.asarray(x_test1)
X_test2=np.asarray(x_test2)
Y_test1=np.asarray(y_test1)
Y_test2=np.asarray(y_test2)

In [11]:
X_train1.shape

(25000, 32, 32, 3)

In [12]:
X_train2

array([[[[ 59,  62,  63],
         [ 43,  46,  45],
         [ 50,  48,  43],
         ...,
         [158, 132, 108],
         [152, 125, 102],
         [148, 124, 103]],

        [[ 16,  20,  20],
         [  0,   0,   0],
         [ 18,   8,   0],
         ...,
         [123,  88,  55],
         [119,  83,  50],
         [122,  87,  57]],

        [[ 25,  24,  21],
         [ 16,   7,   0],
         [ 49,  27,   8],
         ...,
         [118,  84,  50],
         [120,  84,  50],
         [109,  73,  42]],

        ...,

        [[208, 170,  96],
         [201, 153,  34],
         [198, 161,  26],
         ...,
         [160, 133,  70],
         [ 56,  31,   7],
         [ 53,  34,  20]],

        [[180, 139,  96],
         [173, 123,  42],
         [186, 144,  30],
         ...,
         [184, 148,  94],
         [ 97,  62,  34],
         [ 83,  53,  34]],

        [[177, 144, 116],
         [168, 129,  94],
         [179, 142,  87],
         ...,
         [216, 184, 140],
        

In [0]:
X_train1 = X_train1.reshape(X_train1.shape[0], 32, 32, 3) 
X_test1= X_test1.reshape(X_test1.shape[0], 32, 32, 3) 

In [14]:
X_train1[0]

array([[[ 28,  25,  10],
        [ 37,  34,  19],
        [ 38,  35,  20],
        ...,
        [ 76,  67,  39],
        [ 81,  72,  43],
        [ 85,  76,  47]],

       [[ 33,  28,  13],
        [ 34,  30,  14],
        [ 32,  27,  12],
        ...,
        [ 95,  82,  55],
        [ 96,  82,  56],
        [ 85,  72,  45]],

       [[ 39,  32,  15],
        [ 40,  33,  17],
        [ 57,  50,  33],
        ...,
        [ 93,  76,  52],
        [107,  89,  66],
        [ 95,  77,  54]],

       ...,

       [[ 83,  73,  52],
        [ 87,  77,  56],
        [ 84,  74,  52],
        ...,
        [ 99,  93,  70],
        [ 90,  84,  61],
        [ 81,  75,  52]],

       [[ 88,  72,  51],
        [ 90,  74,  52],
        [ 93,  77,  56],
        ...,
        [ 80,  74,  53],
        [ 76,  70,  49],
        [ 82,  76,  55]],

       [[ 97,  78,  56],
        [ 94,  75,  53],
        [ 93,  75,  53],
        ...,
        [ 54,  47,  28],
        [ 63,  56,  37],
        [ 72,  65,  46]]

In [0]:
X_train1=X_train1.astype('float32')
X_test1=X_test1.astype('float32')
X_train1/=255
X_test1/=255

### 2. Use One-hot encoding to divide y_train and y_test into required no of output classes

In [16]:
import numpy as np
np.unique(Y_train1)

array([0, 1, 2, 3, 4], dtype=uint8)

In [17]:

np.unique(Y_test1)

array([0, 1, 2, 3, 4])

In [0]:
Y_train1 = tf.keras.utils.to_categorical(Y_train1, num_classes=5)



In [19]:
Y_train1[0]

array([0., 0., 0., 0., 1.], dtype=float32)

In [0]:
Y_test1 = tf.keras.utils.to_categorical(Y_test1, num_classes=5)

### 3. Build a sequential neural network model which can classify the classes 0 to 4 of CIFAR10 dataset with at least 80% accuracy on test data

In [0]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D

In [49]:
!pip install keras

In [0]:
from keras.preprocessing.image import ImageDataGenerator
datagen = ImageDataGenerator(
    featurewise_center=True,
    featurewise_std_normalization=True,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True)
datagen.fit(X_train1)

In [0]:
from keras.optimizers import Adam
#Initialize the model
model = Sequential()

#Add a Convolutional Layer with 32 filters of size 3X3 and activation function as 'ReLU' 
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=(32,32,3),name='conv_1'))

#Add a Convolutional Layer with 64 filters of size 3X3 and activation function as 'ReLU' 
model.add(Conv2D(32, (3, 3),
                 input_shape=(32,32,3), activation='relu',name='conv_2'))

#Add a MaxPooling Layer of size 2X2 
model.add(MaxPooling2D(pool_size=(2, 2),name='max_1'))

#Apply Dropout with 0.25 probability 
model.add(Dropout(0.25,name='drop_1'))



In [0]:
#Flatten the layer
model.add(Flatten())

#Add Fully Connected Layer with 128 units and activation function as 'ReLU'
model.add(Dense(128, activation='relu',name='dense_1'))

#Add Fully Connected Layer with 128 units and activation function as 'ReLU'
model.add(Dense(128, activation='relu',name='dense_2'))

#Apply Dropout with 0.5 probability 
model.add(Dropout(0.25,name='drop_2'))

#Add Fully Connected Layer with 10 units and activation function as 'softmax'
model.add(Dense(5, activation='softmax',name='dense_3'))
optimizer=Adam(lr=0.001)

In [131]:
model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])
#Train the model
model.fit(X_train1,Y_train1,      
          validation_data=(X_test1,Y_test1),
          epochs=20,
          batch_size=32)

Train on 25000 samples, validate on 5000 samples
Epoch 1/20
25000/25000 [==============================] - 9s 380us/step - loss: 0.9976 - acc: 0.5918 - val_loss: 0.8219 - val_acc: 0.6914
Epoch 2/20
25000/25000 [==============================] - 9s 349us/step - loss: 0.7299 - acc: 0.7184 - val_loss: 0.6688 - val_acc: 0.7386
Epoch 3/20
25000/25000 [==============================] - 9s 348us/step - loss: 0.6237 - acc: 0.7619 - val_loss: 0.6425 - val_acc: 0.7524
Epoch 4/20
25000/25000 [==============================] - 9s 348us/step - loss: 0.5411 - acc: 0.7974 - val_loss: 0.6139 - val_acc: 0.7668
Epoch 5/20
25000/25000 [==============================] - 9s 348us/step - loss: 0.4733 - acc: 0.8228 - val_loss: 0.6232 - val_acc: 0.7668
Epoch 6/20
25000/25000 [==============================] - 9s 348us/step - loss: 0.4003 - acc: 0.8506 - val_loss: 0.6696 - val_acc: 0.7616
Epoch 7/20
25000/25000 [==============================] - 9s 347us/step - loss: 0.3374 - acc: 0.8735 - val_loss: 0.6472 - v

In [132]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
model.save_weights("/content/drive/My Drive/AI_ML/Residency 8 lab/cifar10_weights.h5")

### 4. In the model which was built above (for classification of classes 0-4 in CIFAR10), make only the dense layers to be trainable and conv layers to be non-trainable

In [0]:
#The pre-trained weights must exist in a folder called "data" in the current folder
model.load_weights('/content/drive/My Drive/AI_ML/Residency 8 lab/cifar10_weights.h5')

In [139]:
#Freezing layers in the model which don't have 'dense' in their name
for layer in model.layers:
  if('dense' not in layer.name): #prefix detection to freeze layers which does not have dense
    #Freezing a layer
    layer.trainable = False

#Module to print colourful statements
from termcolor import colored

#Check which layers have been frozen 
for layer in model.layers:
  print (colored(layer.name, 'blue'))
  print (colored(layer.trainable, 'red'))

conv_1
False
conv_2
False
max_1
False
drop_1
False
flatten_6
False
dense_1
True
dense_2
True
drop_2
False
dense_3
True


In [0]:
from keras.optimizers import Adam
from keras.losses import categorical_crossentropy

#To use adam optimizer for learning weights with learning rate = 0.001
optimizer = Adam(lr=0.001)
#Set the loss function and optimizer for the model training
model.compile(loss=categorical_crossentropy,
              optimizer=optimizer,
              metrics=['accuracy'])

In [0]:
X_train2 = X_train2.reshape(X_train2.shape[0], 32, 32, 3)   ## grey scale image and hence adding 1
X_test2 = X_test2.reshape(X_test2.shape[0], 32, 32, 3)

In [0]:
X_train2 = X_train2.astype('float32')
X_test2 = X_test2.astype('float32')
X_train2 /= 255
X_test2 /= 255

In [144]:
from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
Y_train2 = encoder.fit_transform(Y_train2)
Y_test2 = encoder.fit_transform(Y_test2)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [0]:
Y_train2 = tf.keras.utils.to_categorical(Y_train2, num_classes=5)
Y_test2 = tf.keras.utils.to_categorical(Y_test2, num_classes=5)

In [146]:
#Training on the dataset
hist = model.fit(X_train2, Y_train2,
          batch_size=32,
          epochs=20,
          verbose=1,
          validation_data=(X_test2, Y_test2))

Train on 25000 samples, validate on 5000 samples
Epoch 1/20
25000/25000 [==============================] - 7s 277us/step - loss: 1.2076 - acc: 0.6384 - val_loss: 0.5532 - val_acc: 0.7910
Epoch 2/20
25000/25000 [==============================] - 6s 250us/step - loss: 0.5035 - acc: 0.8164 - val_loss: 0.4631 - val_acc: 0.8300
Epoch 3/20
25000/25000 [==============================] - 6s 249us/step - loss: 0.3792 - acc: 0.8626 - val_loss: 0.4488 - val_acc: 0.8438
Epoch 4/20
25000/25000 [==============================] - 6s 249us/step - loss: 0.2945 - acc: 0.8893 - val_loss: 0.4526 - val_acc: 0.8440
Epoch 5/20
25000/25000 [==============================] - 6s 248us/step - loss: 0.2296 - acc: 0.9157 - val_loss: 0.4634 - val_acc: 0.8456
Epoch 6/20
25000/25000 [==============================] - 6s 249us/step - loss: 0.1744 - acc: 0.9360 - val_loss: 0.5185 - val_acc: 0.8468
Epoch 7/20
25000/25000 [==============================] - 6s 251us/step - loss: 0.1429 - acc: 0.9477 - val_loss: 0.5537 - v

### 5. Utilize the the model trained on CIFAR 10 (classes 0 to 4) to classify the classes 5 to 9 of CIFAR 10  (Use Transfer Learning) <br>
Achieve an accuracy of more than 85% on test data

In [148]:
print("test accuracy------>",model.evaluate(X_test2, Y_test2))

5000/5000 [==============================] - 1s 104us/step
test accuracy------> [0.8639040198922158, 0.8526]


# Text classification using TF-IDF

### 6. Load the dataset from sklearn.datasets

In [0]:
from sklearn.datasets import fetch_20newsgroups

In [0]:
categories = ['alt.atheism', 'soc.religion.christian', 'comp.graphics', 'sci.med']

### 7. Training data

In [0]:
twenty_train = fetch_20newsgroups(subset='train', categories=categories, shuffle=True, random_state=42)

### 8. Test data

In [0]:
twenty_test = fetch_20newsgroups(subset='test', categories=categories, shuffle=True, random_state=42)

###  a.  You can access the values for the target variable using .target attribute 
###  b. You can access the name of the class in the target variable with .target_names


In [81]:
np.unique(twenty_train.target)

array([0, 1, 2, 3])

In [82]:
twenty_train.target_names

['alt.atheism', 'comp.graphics', 'sci.med', 'soc.religion.christian']

In [83]:
twenty_train.data[0:5]

['From: sd345@city.ac.uk (Michael Collier)\nSubject: Converting images to HP LaserJet III?\nNntp-Posting-Host: hampton\nOrganization: The City University\nLines: 14\n\nDoes anyone know of a good way (standard PC application/PD utility) to\nconvert tif/img/tga files into LaserJet III format.  We would also like to\ndo the same, converting to HPGL (HP plotter) files.\n\nPlease email any response.\n\nIs this the correct group?\n\nThanks in advance.  Michael.\n-- \nMichael Collier (Programmer)                 The Computer Unit,\nEmail: M.P.Collier@uk.ac.city                The City University,\nTel: 071 477-8000 x3769                      London,\nFax: 071 477-8565                            EC1V 0HB.\n',
 "From: ani@ms.uky.edu (Aniruddha B. Deglurkar)\nSubject: help: Splitting a trimming region along a mesh \nOrganization: University Of Kentucky, Dept. of Math Sciences\nLines: 28\n\n\n\n\tHi,\n\n\tI have a problem, I hope some of the 'gurus' can help me solve.\n\n\tBackground of the probl

### 9.  Now with dependent and independent data available for both train and test datasets, using TfidfVectorizer fit and transform the training data and test data and get the tfidf features for both

In [0]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import pandas as pd
# TfidfVectorizer
vect1 = TfidfVectorizer()
traindf=pd.DataFrame(vect1.fit_transform(twenty_train.data).toarray(), columns=vect1.get_feature_names())

In [110]:
traindf.columns

Index(['00', '000', '0000', '0000001200', '000005102000', '0001',
       '000100255pixel', '00014', '000406', '0007',
       ...
       'zvi', 'zvonko', 'zwart', 'zyeh', 'zyklon', 'zyxel', 'zz', 'zzz', 'ªl',
       'íålittin'],
      dtype='object', length=35788)

In [0]:
testdf=pd.DataFrame(vect1.fit_transform(twenty_test.data).toarray(), columns=vect1.get_feature_names())

In [112]:
testdf.columns

Index(['00', '000', '0000', '000005102000', '0001', '000410', '0007', '000821',
       '000iu', '000mg',
       ...
       'zur', 'zurich', 'zvi', 'zvonko', 'zw10', 'zwingli', 'zyda', 'zyeh',
       'zygon', 'zyxel'],
      dtype='object', length=30786)

In [0]:
X=twenty_test.data

In [0]:
Y=twenty_test.target

In [0]:
X_train=np.asarray(X)
Y_train=np.asarray(Y)

In [97]:
print(X_train.shape)
print(Y_train.shape)

(1502,)
(1502,)


In [0]:
X_test=np.asarray(twenty_test.data)
Y_test=np.asarray(twenty_test.target)

### 10. Use logisticRegression with tfidf features as input and targets as output and train the model and report the train and test accuracy score

In [99]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
# train the model using X_train_dtm
x_id=vect1.fit_transform(X_train)
logreg.fit(x_id, Y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [0]:
x_test_id=vect1.fit_transform(X_test)

In [0]:
# make class predictions for X_test_dtm
y_pred_class = logreg.predict(x_test_id)

In [119]:
# calculate accuracy of class predictions
from sklearn import metrics
# calculate accuracy
print("accuracy----->",metrics.accuracy_score(Y_test, y_pred_class))

accuracy-----> 0.9853528628495339


In [118]:
print("--------First 10 values of the predicted and actual values-------")
for i in range(10):
  print('predicted value----',twenty_train.target_names[y_pred_class[i]],' for actual value----',twenty_train.target_names[Y_test[i]])

--------First 10 values of the predicted and actual values-------
predicted value---- sci.med  for actual value---- sci.med
predicted value---- sci.med  for actual value---- sci.med
predicted value---- sci.med  for actual value---- sci.med
predicted value---- alt.atheism  for actual value---- alt.atheism
predicted value---- soc.religion.christian  for actual value---- soc.religion.christian
predicted value---- alt.atheism  for actual value---- alt.atheism
predicted value---- comp.graphics  for actual value---- comp.graphics
predicted value---- soc.religion.christian  for actual value---- soc.religion.christian
predicted value---- sci.med  for actual value---- sci.med
predicted value---- sci.med  for actual value---- sci.med
